apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      serviceAccountName: my-deployment
      containers:
        - name: my-container
          image: ubuntu:224.04
          imagePullPolicy: IfNotPresent
          command:
            - /usr/bin/cat
          args:
            - /etc/config
          resources:
            limits:
              cpu: 240m
              memory: 192Mi
          volumeMounts:
            - name: my-config
              mountPath: /etc/config
              readOnly: true
      volumes:
        - name: my-config
          configMap:
            name: my-configmap
