apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-namespace
resources:
- namespace.yaml
- role.yaml
- serviceAccount.yaml
- roleBinding.yaml
- service.yaml
- deployment.yaml
configMapGenerator:
- name: my-configmap
  behavior: create
  files:
  - myconfig.json
