apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-service
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: grpc
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
