apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-namespace
resources:
- ../base
patches:
- path: patch-image-pull-secrets.yaml
  target:
    kind: Deployment
    name: ^my-.*$
- path: patch-annotation.yaml
  target:
    kind: Deployment
    name: my-deployment
- path: patch-resource.yaml
